name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  logging: ^1.2.0
  provider: ^6.1.5
  socket_io_client: ^3.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
